### PR TITLE
travis.yml: add the build_ci script

### PR DESCRIPTION
**Pull request by phongt**
reference applied PR from AP-CoreTypes https://github.com/UmlautSoftwareDevelopmentAccount/AP-CoreTypes/pull/49

- Add build_ci.sh for building and running, generation code coverage 
- Use the build_ci.sh script in travis.yml

### CODE REVIEW

**Comment by phongt** [comment]
2 build failure happen in [Build #24](https://travis-ci.org/github/UmlautSoftwareDevelopmentAccount/AP-Functional-Cluster-Template/builds/703516258)

> error: declaration of 'writer' shadows a global declaration [-Werror=shadow]

Track by https://github.com/UmlautSoftwareDevelopmentAccount/AP-Functional-Cluster-Template/issues/21

>error: unknown warning option '-Wduplicated-cond' [-Werror,-Wunknown-warning-option]
>error: unknown warning option '-Wduplicated-branches' [-Werror,-Wunknown-warning-option]
>error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Werror,-Wunknown-warning-option]
>error: unknown warning option '-Wuseless-cast' [-Werror,-Wunknown-warning-option]

Those compiler cpp flags don't recognize by clang.

**Comment by phongt** [comment]
> 
> > error: unknown warning option '-Wduplicated-cond' [-Werror,-Wunknown-warning-option]
> > error: unknown warning option '-Wduplicated-branches' [-Werror,-Wunknown-warning-option]
> > error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Werror,-Wunknown-warning-option]
> > error: unknown warning option '-Wuseless-cast' [-Werror,-Wunknown-warning-option]
> 
> Those compiler cpp flags don't recognize by clang.

Fixed by 8f7b6d4

**Comment by bburda** [comment]
I think, that you can just remove `-Wshadow` for now, and we can merge this change.

**Comment by phongt** [comment]
> I think, that you can just remove `-Wshadow` for now, and we can merge this change.

@bburda  Ok. done in 6361d67

just for notice fmt  were fixed by

https://github.com/fmtlib/fmt/commit/c3fa33314045cb4a132eef9a94524fb073a1e696
https://github.com/fmtlib/fmt/commit/d6cea50d01d7779ecb5ae4da0d785d9bba47a2f7

But the spdlog conan package have not used that version yet.

**Pull request merged**
