### PR TITLE
Change column limit to 100 in clang-format

### PR DESCRIPTION
**Pull request by hliberacki**
#29

### CODE REVIEW

**Review by bburda — CHANGES_REQUESTED** [review]
It is ok for me to increase the column size. Just remember that we have the clang-format setting in the Travis, so you need to also **clang-format the code** here, and during the sync, with CoreTypes, the formatting needs to be also done there. There are few cases where the 80 char column limit introduces confusion in reading the code, like in enums documentation or metaprogramming. I can approve it, but I will wait some time for others to comment on this. I am sure that @slci was the one who first proposed it in the Gitter chat, and the @insooth was against it.

**Comment by slci** [comment]
> [...] I can approve it, but I will wait some time for others to comment on this. I am sure that @slci was the one who first proposed it in the Gitter chat, and the @insooth was against it.

I'm totally for 120 lines. ;)

**Comment by insooth** [comment]
120 is a bit too much, that's 50% more text for eye jumping... 100 shall be enough, and I believe that there will be individual cases where the 80 is exceeded anyway.

**Comment by bburda** [comment]
So @hliberacki @slci are you ok with it? Can we go with a 100 char column limit?

**Comment by hliberacki** [comment]
I think 100 can be a good compromise

**Comment by slci** [comment]
Yeah, 100 is always better than 80. I agree that 120 is far more than typical human can make an eye-fix for reading. But this is only valid when we want to read the code as novel. I don't see a problem with formatted code though.
I tried to find out a way of formatting in-line Doxygen comments (those are the most problematic IMO) but there seems to be no rules to make it nice. I'd love to have different limit for code and for comments, but for now we can make a compromise.
What about 113? Nice, prime number ;)

**Review by slci — APPROVED** [review]

**Comment by bburda** [comment]
Ok, so it seems that we have an agreement. @hliberacki, please change the Issue and the PR names to be adequate to this change. Moreover, it looks like the spdlog version changed, and now causing a crash. Could you also handle it?

**Comment by hliberacki** [comment]
Ok I will handle it

**Review by bburda — APPROVED** [review]
Looks good.

**Pull request merged**
